/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Alumno;
import entidades.Materia;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laucha
 */
public class viewMostrarAlumnos extends javax.swing.JInternalFrame {
    private HashSet<Materia> setmat;
    private HashSet<Alumno>  setalu;
    DefaultTableModel model;
    /**
     * Creates new form NewJInternalFrame
     */
    public viewMostrarAlumnos(HashSet<Alumno> a,HashSet<Materia> m) {
        initComponents();
        model = new DefaultTableModel();
        setalu=a;
        setmat=m;
        llenarLista();
        cabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlNombres = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMaterias = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtSalir1 = new javax.swing.JButton();

        jlNombres.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlNombres.setName(""); // NOI18N
        jlNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlNombresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlNombres);

        jtMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Materia", "Año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtMaterias);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Inscripciones Actuales");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Alumnos");

        jbtSalir1.setText("Salir");
        jbtSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jbtSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 31, Short.MAX_VALUE)
                .addComponent(jbtSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlNombresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlNombresMouseClicked
        borrarLista();
        try {
            Alumno a = jlNombres.getSelectedValue();
            for(Materia m:a.getMaterias()){
                model.addRow(new Object[]{m.getIdMateria(),m.getNombre(),m.getAnio()});
            }
            jtMaterias.setModel(model);
        } catch(NullPointerException npe){
            JOptionPane.showMessageDialog(this, "No se encontraron alumnos para mostrar.");
        }
    }//GEN-LAST:event_jlNombresMouseClicked

    private void jbtSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalir1ActionPerformed
        dispose();
    }//GEN-LAST:event_jbtSalir1ActionPerformed
    private void llenarLista(){
        DefaultListModel<Alumno> lista=new DefaultListModel<>();
        for (Alumno a:setalu){
            lista.addElement(a);
        }
        jlNombres.setModel(lista);
    }
    
    private void cabecera(){
        ArrayList<Object> col = new ArrayList<>();
        col.add("ID");
        col.add("Nombre");
        col.add("Año");
        
        for (Object a:col){
            model.addColumn(a);
        }
        jtMaterias.setModel(model);
    }
    
    private void borrarLista(){
        for (int a=model.getRowCount()-1;a>=0;a--){
            model.removeRow(a);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtSalir1;
    private javax.swing.JList<Alumno> jlNombres;
    private javax.swing.JTable jtMaterias;
    // End of variables declaration//GEN-END:variables
}
